apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-root-password
  namespace: gitlab-system
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: eso-admin-secret-store
    kind: ClusterSecretStore
  target:
    name: gitlab-root-password
  data:
  - secretKey: gitlab-pass
    remoteRef:
      key: demo
      property: gitlab-pass