apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- external-secret.yaml
# - scc.yaml

helmCharts:
- name: gitlab
  namespace: version-control
  releaseName: repository
  repo: https://charts.gitlab.io/
  version: 1.5.4
  valuesInline:
    certmanager-issuer:
      email: cengleby@redhat.com
    gitlab:
      migrations:
        initialRootPassword:
          key: gitlab-pass
          secret: gitlab-root-password
    global:
      edition: ce
      hosts:
        domain: apps.utxcznzv.eastus.aroapp.io
