---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/gitlab-operator-kubernetes.gitlab-system: ""
  name: gitlab-operator-kubernetes
  namespace: gitlab-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: gitlab-operator-kubernetes
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: gitlab-operator-kubernetes.v0.29.0
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: repository
  namespace: gitlab-system
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: gitlab-nginx-ingress-controller
    weight: 100
  wildcardPolicy: None
