apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml

helmCharts:
- name: gitea
  namespace: version-control
  releaseName: repository
  repo: https://dl.gitea.com/charts/
  version: 10.1.3
  valuesInline:
    serviceAccount:
      create: true
