apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml

helmCharts:
- name: gitea
  namespace: version-control
  releaseName: repository
  repo: https://dl.gitea.com/charts/
  version: 1.21.7