apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- scc.yaml

helmCharts:
- name: gitea
  namespace: version-control
  releaseName: repository
  repo: https://charts.bitnami.com/bitnami
  version: 1.5.4
