apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# - route.yaml
# - scc.yaml

helmCharts:
- name: gogs
  namespace: version-control
  releaseName: repository
  repo: https://charts.helm.sh/incubator
  version: 0.7.14
